name: Release

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Bump version and push tag
              uses: Magikon/github-tag-action@v5.0.0
              id: tag
              env:
                RELEASE_BRANCHES: main
                WITH_V: true
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: steps.tag.outputs.new_tag
            