name: Release

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.merge_commit_sha }}
                fetch-depth: '0'
        
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@v1
              env:
                WITH_V: true
                PRERELEASE: true
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ steps.tag.outputs.new_tag}}
            